# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d79086499c7a8abb6e851f453102866f51b55326819a57000b2ae1983b0270cf3c90e346b3691890ba6d71d4179328ade07a8a24e3535187826c7a76ae8b9a3

test:
  secret_key_base: 77571eb47a31e10963fcc3b7fe1608c098a4bf707ed0c929f72eb56fd0c644e7288c3dec5dcad24263806886fdedea5e0bfc5bd8f1a5bd291fe22c1d43db3416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
